apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn-server
  labels:
    app: openvpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openvpn
  template:
    metadata:
      labels:
        app: openvpn
    spec:
      containers:
        - name: openvpn-server
          image: quay.io/izelenov/openvpn-server:ubi
          imagePullPolicy: Always
          ports:
            - containerPort: 1194
          env: 
            - name: OPENVPN_USER
              value: vpnuser
            - name: OPENVPN_PASS
              value: vpnuserPASS42
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "MKNOD", "NET_RAW"]
