apiVersion: v1
kind: Service
metadata:
  name: openvpn
  labels:
    app: openvpn
spec:
  type: NodePort
  selector:
    app: openvpn

  ports:
    - name: openvpn
      port: 1194
      targetPort: 1194
      nodePort: 31194

